import { Options } from '../interface/interfaces';

export const defaults: Options = {
    dataSource: [],
    locator: 'data',
    totalNumber: 0,
    totalNumberLocator: null,
    pageNumber: 1,
    pageSize: 10,
    pageRange: 2,
    alias: {
        pageNumber: 'pageNumber',
        pageSize: 'pageSize',
    },
    showPrevious: true,
    showNext: true,
    showPageNumbers: true,
    showNavigator: false,
    hideFirstOnEllipsisShow: false,
    hideLastOnEllipsisShow: false,
    autoHidePrevious: false,
    autoHideNext: false,
    classPrefix: 'pagination',
    className: '',
    activeClassName: 'active',
    disableClassName: 'disabled',
    ulClassName: '',
    pageClassName: '',
    prevClassName: '',
    nextClassName: '',
    prevText: '&laquo;',
    nextText: '&raquo;',
    ellipsisText: '...',
    goButtonText: 'Go',
    formatNavigator: '{currentPage} of {totalPage}',
    header: '',
    footer: '',
    pageLink: '',
    position: 'bottom',
    formatResult: (data: any) => data,
    dataLoader: {
        method: 'GET',
        data: {},
        cache: 'no-cache',
        headers: {
            'Content-Type': 'application/json'
        },
        mode: 'cors',
        beforeSend: (pagination: any) => pagination,
        credentials: 'same-origin',
        pageNumberStartWithZero: false
    },
    triggerPagingOnInit: true,
    resetPageNumberOnInit: false,
    hideOnlyOnePage: false,
    onError: (err: unknown) => console.error('Pagination error:', err)
};
